# Generated by Django 3.1.6 on 2021-02-13 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210213_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='ge',
        ),
        migrations.AddField(
            model_name='announcement',
            name='de',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5847923d-4845-4edd-be22-e3fca30ec1e8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
