# Generated by Django 3.1.6 on 2021-02-13 19:41

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210213_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_announcements', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='last_modified',
            new_name='modified',
        ),
        migrations.AddField(
            model_name='announcement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ed83773e-3a12-479e-af34-645fdc30da50'), editable=False, primary_key=True, serialize=False),
        ),
    ]
