# Generated by Django 3.1.6 on 2021-02-13 20:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210213_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='modified',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3a613353-cf4e-4dda-a091-2e23c40a3cf6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a7d22a80-7787-42fc-9983-56419d0bf0d1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
