# Generated by Django 3.1.6 on 2021-02-19 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210213_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='num_of_announcements',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='value',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
