# Generated by Django 3.1.6 on 2021-02-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210219_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(max_length=48, primary_key=True, serialize=False),
        ),
    ]
