# Generated by Django 3.1.6 on 2021-02-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210220_0012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcement',
            new_name='AnnouncementModel',
        ),
        migrations.RenameModel(
            old_name='GlobalSettings',
            new_name='GlobalSettingsModel',
        ),
    ]
